sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t s2i-openjdk18-alpine  .
  -  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  -  docker push vguar/s2i-openjdk18-alpine
